apiVersion: apps/v1
kind: Deployment
metadata:
  name: redis-app-deployment.yml
  labels:
    name: redis-app-deployment.yml
    author: doh
spec:
  replicas: 2
  selector:
    matchLabels:
      name: redis-app-deployment.yml
  template:
    metadata:
      name: redis-app-pod
      labels:
        name: redis-app-deployment.yml
    spec:
      containers:
        - name: redis-db
          image: redis
          ports:
            - containerPort: 6379
