---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: Voting-app-deeployment
  labels:
    name: Voting-app-deeployment
    author: doh
spec:
  replicas: 2
  selector:
    matchLabels:
      name: Voting-app-deeployment
  template:
    metadata:
      name: voting-pod
      labels:
        name: Voting-app-deeployment
    spec:
      containers:
        - name: voting-app
          image: dockersamples/examplevotingapp_vote
          ports:
            - containerPort: 80
...